Fix: Change input handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -23,12 +23,11 @@ inputs:
     description: "Uploads test/coverage report bundle as artefact"
     required: false
     type: boolean
-    default: false
+    default: true
   PATH_PREFIX:
     description: "Directory location containing Python project code"
     type: string
     required: false
-    default: ""
   TESTS_PATH:
     description: "Path relative to the project folder containing tests"
     required: false
@@ -42,7 +41,7 @@ inputs:
     description: "Space separated list of tox environments to run"
     required: false
     type: string
-    default: "tests lint"
+    default: "lint tests"
 
 runs:
   using: "composite"
@@ -52,85 +51,69 @@ runs:
       run: |
         # Setup action/environment
         if [ -z "${{ inputs.python_version }}" ]; then
-          echo "Error: Python version was not provided ❌"
-          exit 1
+          echo "Error: Python version was not provided ❌"; exit 1
         else
           echo "Using Python: ${{ inputs.python_version }} 🐍"
         fi
 
-        # Check for yq command required to extract dependencies
-        if !(which -s yq); then
-          echo "Error: yq command NOT found ❌"
-          exit 1
+        # Handle path_prefix input consistently and when absent
+        path_prefix="${{ inputs.PATH_PREFIX }}"
+        if [ -z "$path_prefix" ]; then
+          # Set current directory as path prefix
+          path_prefix="."
+        else
+          # Strip any trailing slash in provided path
+          path_prefix="${path_prefix%/}"
         fi
-
-        # Check path_prefix is a valid directory
-        path_prefix="${{ inputs.path_prefix }}"
-        if [ -n "$path_prefix" ] && \
-          [ ! -d "$path_prefix" ]; then
-          echo "Error: invalid path/prefix to project directory ❌"
-          exit 1
+        # Verify is a valid directory path
+        if [ ! -d "$path_prefix" ]; then
+          echo "Error: invalid path/prefix to project directory ❌"; exit 1
         fi
+        echo "path_prefix=$path_prefix" >> "$GITHUB_ENV"
 
-        # Check the provided tests_path exists
-        if [ -n "${{ inputs.tests_path }}" ] && \
-          [ ! -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
-          echo "Error: invalid path/prefix to test directory ❌"
-          echo "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
-          exit 1
-        fi
-
-        # Handle boolean inputs
-        permit_fail=$(echo "${{ inputs.permit_fail }}" |\
-        tr '[:upper:]' '[:lower:]')
-        if [ "f$permit_fail" = "ftrue" ]; then
+        if [ "f${{ inputs.PERMIT_FAIL }}" = "ftrue" ]; then
           echo "Warning: test failures will be permitted ⚠️"
-          echo "permit_fail=true" >> "$GITHUB_ENV"
         fi
-        report_artefact=$(echo "${{ inputs.report_artefact }}" |\
-        tr '[:upper:]' '[:lower:]')
-        if [ "f$report_artefact" = "ftrue" ]; then
-          echo "Coverage report artefacts enabled 💬"
-          echo "report_artefact=true" >> "$GITHUB_ENV"
-        fi
-        tox_tests=$(echo "${{ inputs.tox_tests }}" |\
-        tr '[:upper:]' '[:lower:]')
-        if [ "f$tox_tests" = "ftrue" ]; then
+
+        if [ "f${{ inputs.TOX_TESTS }}" = "ftrue" ]; then
           echo "Using tox to perform tests 💬"
-          echo "tox_tests=true" >> "$GITHUB_ENV"
-          if [ -z ${{ inputs.tox_envs }} ]; then
+          if [ -z "${{ inputs.TOX_ENVS }}" ]; then
             echo "Error: no tox environments were specified ❌"; exit 1
           else
-            echo "Tox environments to run: ${{ inputs.tox_envs }} 💬"
+            echo "Tox environments: ${{ inputs.TOX_ENVS }} 💬"
           fi
         fi
 
         # Check/setup test path
+        if [ -n "${{ inputs.tests_path }}" ] && \
+          [ ! -d "$path_prefix/${{ inputs.tests_path }}" ]; then
+          echo "Error: invalid path/prefix to test directory ❌"
+          echo "$path_prefix/${{ inputs.tests_path }}"; exit 1
+        fi
         if [ -n "${{ inputs.tests_path }}" ]; then
-          TESTS_PATH="${{ inputs.path_prefix }}${{ inputs.tests_path }}"
-        # Otherwise use common locations
-        elif [ -d "${{ inputs.path_prefix }}tests" ]; then
-          TESTS_PATH="${{ inputs.path_prefix }}tests"
-        elif [ -d "${{ inputs.path_prefix }}test" ]; then
-          TESTS_PATH="${{ inputs.path_prefix }}test"
+          TESTS_PATH="$path_prefix/${{ inputs.tests_path }}"
+        # Otherwise search/use common locations
+        elif [ -d "$path_prefix/test" ]; then
+          TESTS_PATH="$path_prefix/test"
+        elif [ -d "$path_prefix/tests" ]; then
+          TESTS_PATH="$path_prefix/tests"
         else
-          echo "Error: no valid test path was found ❌"
-          exit 1
+          echo "Error: could not determine path to tests ❌"; exit 1
         fi
         echo "Tests path: $TESTS_PATH 💬"
         echo "tests_path=$TESTS_PATH" >> "$GITHUB_ENV"
 
     - name: "Check for tox configuration file"
-      if: ${{ env.tox_tests }} == 'true'
+      if: inputs.TOX_TESTS == 'true'
       id: tox-config
       # yamllint disable-line rule:line-length
       uses: lfreleng-actions/path-check-action@554ef2267e6810ab7ac56506c8c1fd00725d59b1 # v0.1.0
       with:
-        path: "${{ inputs.path_prefix }}tox.ini"
+        path: "${{ env.path_prefix }}/tox.ini"
 
     - name: "Tox configuration file missing"
       # yamllint disable-line rule:line-length
-      if: steps.tox-config.outputs.type != 'file' && env.tox_tests == 'true'
+      if: steps.tox-config.outputs.type != 'file' && inputs.TOX_TESTS == 'true'
       shell: bash
       run: |
         # Tox configuration file missing
@@ -143,37 +126,36 @@ runs:
         python-version: ${{ inputs.python_version }}
 
     - name: "Performing tests [tox]"
-      if: steps.tox-config.outputs.type == 'file' && env.tox_tests == 'true'
+      if: steps.tox-config.outputs.type == 'file' && inputs.TOX_TESTS == 'true'
       shell: bash
       run: |
         # Performing tests [tox]
         echo "Installing: tox ⬇️"
         pip install --disable-pip-version-check -q tox
-        for ENVIRONMENT in ${{ inputs.tox_envs }}; do
-          echo "Running: tox -c ${{ inputs.path_prefix }}tox.ini -e $ENVIRONMENT"
-          tox -c ${{ inputs.path_prefix }}tox.ini -e "$ENVIRONMENT"
+        for ENV in ${{ inputs.TOX_ENVS }}; do
+          echo "Running: tox -c ${{ env.path_prefix }}/tox.ini -e $ENV 💬"
+          tox -c ${{ env.path_prefix }}/tox.ini -e "$ENV"
         done
 
     - name: "Tests and coverage report [pytest]"
-      if: env.tox_tests != 'true'
+      if: inputs.TOX_TESTS != 'true'
       shell: bash
       run: |
         # Tests and coverage report [pytest]
         echo "Installing: pytest, pytest-cov ⬇️"
         pip install --disable-pip-version-check -q pytest pytest-cov
 
-        echo "Install declared project dependencies"
-        if [ -f ${{ inputs.path_prefix }}pyproject.toml ]; then
-            echo "Source: ${{ inputs.path_prefix }}pyproject.toml ⬇️"
-            yq '.project.dependencies[]' \
-              ${{ inputs.path_prefix }}pyproject.toml |\
-              xargs -r pip -q install
-        elif [ -f ${{ inputs.path_prefix }}requirements.txt ]; then
-          echo "Source: ${{ inputs.path_prefix }}requirements.txt ⬇️"
-          pip install -q -r "${{ inputs.path_prefix }}requirements.txt"
+        echo "Install project and dependencies"
+        if [ -f ${{ env.path_prefix }}/pyproject.toml ]; then
+            echo "Source: ${{ env.path_prefix }}/pyproject.toml ⬇️"
+            pip install -q "${{ env.path_prefix }}/"
+        elif [ -f ${{ env.path_prefix }}/requirements.txt ]; then
+          echo "Source: ${{ env.path_prefix }}/requirements.txt ⬇️"
+          pip install -q -r "${{ env.path_prefix }}/requirements.txt"
         fi
           echo "Running tests in: ${{ env.tests_path }} 🧪"
-        if [ "${{ env.permit_fail }}" = 'true' ]; then
+        if [ "f${{ inputs.permit_fail }}" = 'ftrue' ]; then
+          echo "Warning: flag set to permit test failures ⚠️"
           pytest --cov --cov-report=html:coverage_report \
             ${{ env.tests_path }} || true
         else
@@ -181,22 +163,22 @@ runs:
         fi
 
     - name: "Create ZIP archive of coverage report"
-      if: ${{ env.report_artefact }} == 'true'
+      if: inputs.REPORT_ARTEFACT == 'true'
       shell: bash
       run: |
         # Create ZIP archive of coverage report
         if [ -d coverage_report ]; then
           echo "Creating ZIP file of HTML coverage report"
-          zip -r test_coverage_report-${{ inputs.python_version }}.zip \
+          zip -r test_coverage_report-${{ inputs.PYTHON_VERSION }}.zip \
             coverage_report
         else
           echo "No coverage report directory exists"
         fi
 
     - name: "Upload test/coverage report"
-      if: ${{ env.report_artefact }} == 'true'
       # yamllint disable-line rule:line-length
       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+      if: inputs.REPORT_ARTEFACT == 'true'
       with:
         name: test_coverage_report-${{ inputs.python_version }}.zip
         path: test_coverage_report-${{ inputs.python_version }}.zip
